name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'jeademo1927'
          # Container registry password
          password: 't5RqbPntSKuFo3SH8JPiv7kUq+Ld14lS8V43bsOLgL+ACRA9BC9C'
          # Container registry server url
          login-server: 'jeademo1927.azurecr.io'
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          # tags: <registry server url>/<app name>:<git commit sha>
          tags: jeademo1927.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
      
  deployToAKS:
    permissions:
      actions: read
      contents: read
      id-token: write
  
    runs-on: ubuntu-latest
    needs: [buildImage]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: '558be29a-ed55-48a3-83fa-7e64f270c7e8'
          tenant-id: '91c653f5-2846-431d-98a3-5ddacd2a7283'
          subscription-id: '6bed5a7b-ea2a-447e-9d41-f0615453807b'
        
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'github-actions'
          # AKS Cluster Name
          cluster-name: 'jeak8s1927'
          # AKS Cluster Subscription
          subscription: '6bed5a7b-ea2a-447e-9d41-f0615453807b'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      # Substitute environment variables in a file
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: 'mongodb://jeacosmos1928:ERkZmFPqPSD8jE7dkemesb5ZnEtJLqNGSBKbpE53KK4V1PBn0mrBDKFazbS5O8szmB6airUrIbx9ACDbDyiZdA==@jeacosmos1928.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@jeacosmos1928@'
          CONTAINER_NAME: hello-world-app:${{ github.sha }}
          AZURE_CONTAINER_REGISTRY: jeademo1927.azurecr.io
        with:
          # File to run substitutions on
          input: 
            kubernetes/hello-world-deployment.yaml
          # File to write result to
          output: 
            hello-world-deployment.yaml

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            jeademo1927.azurecr.io/hello-world-app:${{ github.sha }}
            
