name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:
 
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          
          username: jeademo1927
          
          password: t5RqbPntSKuFo3SH8JPiv7kUq+Ld14lS8V43bsOLgL+ACRA9BC9C
      
          login-server: jeademo1927.azurecr.io
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jeademo1927.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
      
  deployToAKS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
